version: '3'

services:
  postgres:
    image: docker.io/postgres:${CONFIG_VERSION}
    command: /postgres-init.sh
    environment:
    - POSTGRES_USER=angle
    - POSTGRES_PASSWORD=angle
    volumes:
    - socket:/var/run/postgresql
    - ../../../tests/data/postgres-init.sh:/postgres-init.sh:ro
    - ../../../tests/data/ca:/certs:ro

volumes:
  socket: {}
