apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: angle

resources:
  - configmap.yaml
  - service-headless.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml
